"""Migração Inicial

Revision ID: 23cb9877ffb2
Revises: 
Create Date: 2024-09-06 14:19:28.036802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cb9877ffb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departamentos',
    sa.Column('id_departamentos', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('numero_funcionarios', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_departamentos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Departamentos')
    # ### end Alembic commands ###
